version: '3.7'

services:
  todo_app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
      - ./src/app.html:/home/node/app/src/app.html
    container_name: todo_app
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev